// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol-buffer-generate-code/proto/student.proto

package io.github.manojpawar94.proto.example;

public final class StudentOuterClass {
  private StudentOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StudentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.github.manojpawar94.proto.example.Student)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 student_id = 1;</code>
     * @return The studentId.
     */
    long getStudentId();

    /**
     * <code>string first_name = 2;</code>
     * @return The firstName.
     */
    java.lang.String getFirstName();
    /**
     * <code>string first_name = 2;</code>
     * @return The bytes for firstName.
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <code>string last_name = 3;</code>
     * @return The lastName.
     */
    java.lang.String getLastName();
    /**
     * <code>string last_name = 3;</code>
     * @return The bytes for lastName.
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    /**
     * <code>.io.github.manojpawar94.proto.example.Student.Standard standard = 4;</code>
     * @return The enum numeric value on the wire for standard.
     */
    int getStandardValue();
    /**
     * <code>.io.github.manojpawar94.proto.example.Student.Standard standard = 4;</code>
     * @return The standard.
     */
    io.github.manojpawar94.proto.example.StudentOuterClass.Student.Standard getStandard();

    /**
     * <code>repeated .io.github.manojpawar94.proto.example.Address addresses = 5;</code>
     */
    java.util.List<io.github.manojpawar94.proto.example.AddressOuterClass.Address> 
        getAddressesList();
    /**
     * <code>repeated .io.github.manojpawar94.proto.example.Address addresses = 5;</code>
     */
    io.github.manojpawar94.proto.example.AddressOuterClass.Address getAddresses(int index);
    /**
     * <code>repeated .io.github.manojpawar94.proto.example.Address addresses = 5;</code>
     */
    int getAddressesCount();
    /**
     * <code>repeated .io.github.manojpawar94.proto.example.Address addresses = 5;</code>
     */
    java.util.List<? extends io.github.manojpawar94.proto.example.AddressOuterClass.AddressOrBuilder> 
        getAddressesOrBuilderList();
    /**
     * <code>repeated .io.github.manojpawar94.proto.example.Address addresses = 5;</code>
     */
    io.github.manojpawar94.proto.example.AddressOuterClass.AddressOrBuilder getAddressesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code io.github.manojpawar94.proto.example.Student}
   */
  public static final class Student extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.github.manojpawar94.proto.example.Student)
      StudentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Student.newBuilder() to construct.
    private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Student() {
      firstName_ = "";
      lastName_ = "";
      standard_ = 0;
      addresses_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Student();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Student(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              studentId_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              firstName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              lastName_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              standard_ = rawValue;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                addresses_ = new java.util.ArrayList<io.github.manojpawar94.proto.example.AddressOuterClass.Address>();
                mutable_bitField0_ |= 0x00000001;
              }
              addresses_.add(
                  input.readMessage(io.github.manojpawar94.proto.example.AddressOuterClass.Address.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          addresses_ = java.util.Collections.unmodifiableList(addresses_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.manojpawar94.proto.example.StudentOuterClass.internal_static_io_github_manojpawar94_proto_example_Student_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.manojpawar94.proto.example.StudentOuterClass.internal_static_io_github_manojpawar94_proto_example_Student_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.manojpawar94.proto.example.StudentOuterClass.Student.class, io.github.manojpawar94.proto.example.StudentOuterClass.Student.Builder.class);
    }

    /**
     * Protobuf enum {@code io.github.manojpawar94.proto.example.Student.Standard}
     */
    public enum Standard
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN_STD = 0;</code>
       */
      UNKNOWN_STD(0),
      /**
       * <code>FIFTH_STD = 1;</code>
       */
      FIFTH_STD(1),
      /**
       * <code>SIXTH_STD = 2;</code>
       */
      SIXTH_STD(2),
      /**
       * <code>SEVENTH_STD = 3;</code>
       */
      SEVENTH_STD(3),
      /**
       * <code>EIGHT_STD = 4;</code>
       */
      EIGHT_STD(4),
      /**
       * <code>NINE_STD = 5;</code>
       */
      NINE_STD(5),
      /**
       * <code>TENTH_STD = 6;</code>
       */
      TENTH_STD(6),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN_STD = 0;</code>
       */
      public static final int UNKNOWN_STD_VALUE = 0;
      /**
       * <code>FIFTH_STD = 1;</code>
       */
      public static final int FIFTH_STD_VALUE = 1;
      /**
       * <code>SIXTH_STD = 2;</code>
       */
      public static final int SIXTH_STD_VALUE = 2;
      /**
       * <code>SEVENTH_STD = 3;</code>
       */
      public static final int SEVENTH_STD_VALUE = 3;
      /**
       * <code>EIGHT_STD = 4;</code>
       */
      public static final int EIGHT_STD_VALUE = 4;
      /**
       * <code>NINE_STD = 5;</code>
       */
      public static final int NINE_STD_VALUE = 5;
      /**
       * <code>TENTH_STD = 6;</code>
       */
      public static final int TENTH_STD_VALUE = 6;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Standard valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Standard forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN_STD;
          case 1: return FIFTH_STD;
          case 2: return SIXTH_STD;
          case 3: return SEVENTH_STD;
          case 4: return EIGHT_STD;
          case 5: return NINE_STD;
          case 6: return TENTH_STD;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Standard>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Standard> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Standard>() {
              public Standard findValueByNumber(int number) {
                return Standard.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return io.github.manojpawar94.proto.example.StudentOuterClass.Student.getDescriptor().getEnumTypes().get(0);
      }

      private static final Standard[] VALUES = values();

      public static Standard valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Standard(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:io.github.manojpawar94.proto.example.Student.Standard)
    }

    public static final int STUDENT_ID_FIELD_NUMBER = 1;
    private long studentId_;
    /**
     * <code>int64 student_id = 1;</code>
     * @return The studentId.
     */
    @java.lang.Override
    public long getStudentId() {
      return studentId_;
    }

    public static final int FIRST_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object firstName_;
    /**
     * <code>string first_name = 2;</code>
     * @return The firstName.
     */
    @java.lang.Override
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      }
    }
    /**
     * <code>string first_name = 2;</code>
     * @return The bytes for firstName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAST_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object lastName_;
    /**
     * <code>string last_name = 3;</code>
     * @return The lastName.
     */
    @java.lang.Override
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      }
    }
    /**
     * <code>string last_name = 3;</code>
     * @return The bytes for lastName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STANDARD_FIELD_NUMBER = 4;
    private int standard_;
    /**
     * <code>.io.github.manojpawar94.proto.example.Student.Standard standard = 4;</code>
     * @return The enum numeric value on the wire for standard.
     */
    @java.lang.Override public int getStandardValue() {
      return standard_;
    }
    /**
     * <code>.io.github.manojpawar94.proto.example.Student.Standard standard = 4;</code>
     * @return The standard.
     */
    @java.lang.Override public io.github.manojpawar94.proto.example.StudentOuterClass.Student.Standard getStandard() {
      @SuppressWarnings("deprecation")
      io.github.manojpawar94.proto.example.StudentOuterClass.Student.Standard result = io.github.manojpawar94.proto.example.StudentOuterClass.Student.Standard.valueOf(standard_);
      return result == null ? io.github.manojpawar94.proto.example.StudentOuterClass.Student.Standard.UNRECOGNIZED : result;
    }

    public static final int ADDRESSES_FIELD_NUMBER = 5;
    private java.util.List<io.github.manojpawar94.proto.example.AddressOuterClass.Address> addresses_;
    /**
     * <code>repeated .io.github.manojpawar94.proto.example.Address addresses = 5;</code>
     */
    @java.lang.Override
    public java.util.List<io.github.manojpawar94.proto.example.AddressOuterClass.Address> getAddressesList() {
      return addresses_;
    }
    /**
     * <code>repeated .io.github.manojpawar94.proto.example.Address addresses = 5;</code>
     */
    @java.lang.Override
    public java.util.List<? extends io.github.manojpawar94.proto.example.AddressOuterClass.AddressOrBuilder> 
        getAddressesOrBuilderList() {
      return addresses_;
    }
    /**
     * <code>repeated .io.github.manojpawar94.proto.example.Address addresses = 5;</code>
     */
    @java.lang.Override
    public int getAddressesCount() {
      return addresses_.size();
    }
    /**
     * <code>repeated .io.github.manojpawar94.proto.example.Address addresses = 5;</code>
     */
    @java.lang.Override
    public io.github.manojpawar94.proto.example.AddressOuterClass.Address getAddresses(int index) {
      return addresses_.get(index);
    }
    /**
     * <code>repeated .io.github.manojpawar94.proto.example.Address addresses = 5;</code>
     */
    @java.lang.Override
    public io.github.manojpawar94.proto.example.AddressOuterClass.AddressOrBuilder getAddressesOrBuilder(
        int index) {
      return addresses_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (studentId_ != 0L) {
        output.writeInt64(1, studentId_);
      }
      if (!getFirstNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lastName_);
      }
      if (standard_ != io.github.manojpawar94.proto.example.StudentOuterClass.Student.Standard.UNKNOWN_STD.getNumber()) {
        output.writeEnum(4, standard_);
      }
      for (int i = 0; i < addresses_.size(); i++) {
        output.writeMessage(5, addresses_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (studentId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, studentId_);
      }
      if (!getFirstNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lastName_);
      }
      if (standard_ != io.github.manojpawar94.proto.example.StudentOuterClass.Student.Standard.UNKNOWN_STD.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, standard_);
      }
      for (int i = 0; i < addresses_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, addresses_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.manojpawar94.proto.example.StudentOuterClass.Student)) {
        return super.equals(obj);
      }
      io.github.manojpawar94.proto.example.StudentOuterClass.Student other = (io.github.manojpawar94.proto.example.StudentOuterClass.Student) obj;

      if (getStudentId()
          != other.getStudentId()) return false;
      if (!getFirstName()
          .equals(other.getFirstName())) return false;
      if (!getLastName()
          .equals(other.getLastName())) return false;
      if (standard_ != other.standard_) return false;
      if (!getAddressesList()
          .equals(other.getAddressesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STUDENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStudentId());
      hash = (37 * hash) + FIRST_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstName().hashCode();
      hash = (37 * hash) + LAST_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastName().hashCode();
      hash = (37 * hash) + STANDARD_FIELD_NUMBER;
      hash = (53 * hash) + standard_;
      if (getAddressesCount() > 0) {
        hash = (37 * hash) + ADDRESSES_FIELD_NUMBER;
        hash = (53 * hash) + getAddressesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.manojpawar94.proto.example.StudentOuterClass.Student parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.manojpawar94.proto.example.StudentOuterClass.Student parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.manojpawar94.proto.example.StudentOuterClass.Student parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.manojpawar94.proto.example.StudentOuterClass.Student parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.manojpawar94.proto.example.StudentOuterClass.Student parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.manojpawar94.proto.example.StudentOuterClass.Student parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.manojpawar94.proto.example.StudentOuterClass.Student parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.manojpawar94.proto.example.StudentOuterClass.Student parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.manojpawar94.proto.example.StudentOuterClass.Student parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.manojpawar94.proto.example.StudentOuterClass.Student parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.manojpawar94.proto.example.StudentOuterClass.Student parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.manojpawar94.proto.example.StudentOuterClass.Student parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.manojpawar94.proto.example.StudentOuterClass.Student prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.github.manojpawar94.proto.example.Student}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.github.manojpawar94.proto.example.Student)
        io.github.manojpawar94.proto.example.StudentOuterClass.StudentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.manojpawar94.proto.example.StudentOuterClass.internal_static_io_github_manojpawar94_proto_example_Student_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.manojpawar94.proto.example.StudentOuterClass.internal_static_io_github_manojpawar94_proto_example_Student_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.manojpawar94.proto.example.StudentOuterClass.Student.class, io.github.manojpawar94.proto.example.StudentOuterClass.Student.Builder.class);
      }

      // Construct using io.github.manojpawar94.proto.example.StudentOuterClass.Student.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAddressesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        studentId_ = 0L;

        firstName_ = "";

        lastName_ = "";

        standard_ = 0;

        if (addressesBuilder_ == null) {
          addresses_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          addressesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.manojpawar94.proto.example.StudentOuterClass.internal_static_io_github_manojpawar94_proto_example_Student_descriptor;
      }

      @java.lang.Override
      public io.github.manojpawar94.proto.example.StudentOuterClass.Student getDefaultInstanceForType() {
        return io.github.manojpawar94.proto.example.StudentOuterClass.Student.getDefaultInstance();
      }

      @java.lang.Override
      public io.github.manojpawar94.proto.example.StudentOuterClass.Student build() {
        io.github.manojpawar94.proto.example.StudentOuterClass.Student result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.github.manojpawar94.proto.example.StudentOuterClass.Student buildPartial() {
        io.github.manojpawar94.proto.example.StudentOuterClass.Student result = new io.github.manojpawar94.proto.example.StudentOuterClass.Student(this);
        int from_bitField0_ = bitField0_;
        result.studentId_ = studentId_;
        result.firstName_ = firstName_;
        result.lastName_ = lastName_;
        result.standard_ = standard_;
        if (addressesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            addresses_ = java.util.Collections.unmodifiableList(addresses_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.addresses_ = addresses_;
        } else {
          result.addresses_ = addressesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.manojpawar94.proto.example.StudentOuterClass.Student) {
          return mergeFrom((io.github.manojpawar94.proto.example.StudentOuterClass.Student)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.manojpawar94.proto.example.StudentOuterClass.Student other) {
        if (other == io.github.manojpawar94.proto.example.StudentOuterClass.Student.getDefaultInstance()) return this;
        if (other.getStudentId() != 0L) {
          setStudentId(other.getStudentId());
        }
        if (!other.getFirstName().isEmpty()) {
          firstName_ = other.firstName_;
          onChanged();
        }
        if (!other.getLastName().isEmpty()) {
          lastName_ = other.lastName_;
          onChanged();
        }
        if (other.standard_ != 0) {
          setStandardValue(other.getStandardValue());
        }
        if (addressesBuilder_ == null) {
          if (!other.addresses_.isEmpty()) {
            if (addresses_.isEmpty()) {
              addresses_ = other.addresses_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAddressesIsMutable();
              addresses_.addAll(other.addresses_);
            }
            onChanged();
          }
        } else {
          if (!other.addresses_.isEmpty()) {
            if (addressesBuilder_.isEmpty()) {
              addressesBuilder_.dispose();
              addressesBuilder_ = null;
              addresses_ = other.addresses_;
              bitField0_ = (bitField0_ & ~0x00000001);
              addressesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAddressesFieldBuilder() : null;
            } else {
              addressesBuilder_.addAllMessages(other.addresses_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.manojpawar94.proto.example.StudentOuterClass.Student parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.manojpawar94.proto.example.StudentOuterClass.Student) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long studentId_ ;
      /**
       * <code>int64 student_id = 1;</code>
       * @return The studentId.
       */
      @java.lang.Override
      public long getStudentId() {
        return studentId_;
      }
      /**
       * <code>int64 student_id = 1;</code>
       * @param value The studentId to set.
       * @return This builder for chaining.
       */
      public Builder setStudentId(long value) {
        
        studentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 student_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStudentId() {
        
        studentId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object firstName_ = "";
      /**
       * <code>string first_name = 2;</code>
       * @return The firstName.
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string first_name = 2;</code>
       * @return The bytes for firstName.
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string first_name = 2;</code>
       * @param value The firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string first_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirstName() {
        
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <code>string first_name = 2;</code>
       * @param value The bytes for firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        firstName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <code>string last_name = 3;</code>
       * @return The lastName.
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string last_name = 3;</code>
       * @return The bytes for lastName.
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string last_name = 3;</code>
       * @param value The lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string last_name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastName() {
        
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <code>string last_name = 3;</code>
       * @param value The bytes for lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lastName_ = value;
        onChanged();
        return this;
      }

      private int standard_ = 0;
      /**
       * <code>.io.github.manojpawar94.proto.example.Student.Standard standard = 4;</code>
       * @return The enum numeric value on the wire for standard.
       */
      @java.lang.Override public int getStandardValue() {
        return standard_;
      }
      /**
       * <code>.io.github.manojpawar94.proto.example.Student.Standard standard = 4;</code>
       * @param value The enum numeric value on the wire for standard to set.
       * @return This builder for chaining.
       */
      public Builder setStandardValue(int value) {
        
        standard_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.io.github.manojpawar94.proto.example.Student.Standard standard = 4;</code>
       * @return The standard.
       */
      @java.lang.Override
      public io.github.manojpawar94.proto.example.StudentOuterClass.Student.Standard getStandard() {
        @SuppressWarnings("deprecation")
        io.github.manojpawar94.proto.example.StudentOuterClass.Student.Standard result = io.github.manojpawar94.proto.example.StudentOuterClass.Student.Standard.valueOf(standard_);
        return result == null ? io.github.manojpawar94.proto.example.StudentOuterClass.Student.Standard.UNRECOGNIZED : result;
      }
      /**
       * <code>.io.github.manojpawar94.proto.example.Student.Standard standard = 4;</code>
       * @param value The standard to set.
       * @return This builder for chaining.
       */
      public Builder setStandard(io.github.manojpawar94.proto.example.StudentOuterClass.Student.Standard value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        standard_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.io.github.manojpawar94.proto.example.Student.Standard standard = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStandard() {
        
        standard_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<io.github.manojpawar94.proto.example.AddressOuterClass.Address> addresses_ =
        java.util.Collections.emptyList();
      private void ensureAddressesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          addresses_ = new java.util.ArrayList<io.github.manojpawar94.proto.example.AddressOuterClass.Address>(addresses_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.github.manojpawar94.proto.example.AddressOuterClass.Address, io.github.manojpawar94.proto.example.AddressOuterClass.Address.Builder, io.github.manojpawar94.proto.example.AddressOuterClass.AddressOrBuilder> addressesBuilder_;

      /**
       * <code>repeated .io.github.manojpawar94.proto.example.Address addresses = 5;</code>
       */
      public java.util.List<io.github.manojpawar94.proto.example.AddressOuterClass.Address> getAddressesList() {
        if (addressesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(addresses_);
        } else {
          return addressesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .io.github.manojpawar94.proto.example.Address addresses = 5;</code>
       */
      public int getAddressesCount() {
        if (addressesBuilder_ == null) {
          return addresses_.size();
        } else {
          return addressesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .io.github.manojpawar94.proto.example.Address addresses = 5;</code>
       */
      public io.github.manojpawar94.proto.example.AddressOuterClass.Address getAddresses(int index) {
        if (addressesBuilder_ == null) {
          return addresses_.get(index);
        } else {
          return addressesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .io.github.manojpawar94.proto.example.Address addresses = 5;</code>
       */
      public Builder setAddresses(
          int index, io.github.manojpawar94.proto.example.AddressOuterClass.Address value) {
        if (addressesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressesIsMutable();
          addresses_.set(index, value);
          onChanged();
        } else {
          addressesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .io.github.manojpawar94.proto.example.Address addresses = 5;</code>
       */
      public Builder setAddresses(
          int index, io.github.manojpawar94.proto.example.AddressOuterClass.Address.Builder builderForValue) {
        if (addressesBuilder_ == null) {
          ensureAddressesIsMutable();
          addresses_.set(index, builderForValue.build());
          onChanged();
        } else {
          addressesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .io.github.manojpawar94.proto.example.Address addresses = 5;</code>
       */
      public Builder addAddresses(io.github.manojpawar94.proto.example.AddressOuterClass.Address value) {
        if (addressesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressesIsMutable();
          addresses_.add(value);
          onChanged();
        } else {
          addressesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .io.github.manojpawar94.proto.example.Address addresses = 5;</code>
       */
      public Builder addAddresses(
          int index, io.github.manojpawar94.proto.example.AddressOuterClass.Address value) {
        if (addressesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressesIsMutable();
          addresses_.add(index, value);
          onChanged();
        } else {
          addressesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .io.github.manojpawar94.proto.example.Address addresses = 5;</code>
       */
      public Builder addAddresses(
          io.github.manojpawar94.proto.example.AddressOuterClass.Address.Builder builderForValue) {
        if (addressesBuilder_ == null) {
          ensureAddressesIsMutable();
          addresses_.add(builderForValue.build());
          onChanged();
        } else {
          addressesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .io.github.manojpawar94.proto.example.Address addresses = 5;</code>
       */
      public Builder addAddresses(
          int index, io.github.manojpawar94.proto.example.AddressOuterClass.Address.Builder builderForValue) {
        if (addressesBuilder_ == null) {
          ensureAddressesIsMutable();
          addresses_.add(index, builderForValue.build());
          onChanged();
        } else {
          addressesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .io.github.manojpawar94.proto.example.Address addresses = 5;</code>
       */
      public Builder addAllAddresses(
          java.lang.Iterable<? extends io.github.manojpawar94.proto.example.AddressOuterClass.Address> values) {
        if (addressesBuilder_ == null) {
          ensureAddressesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, addresses_);
          onChanged();
        } else {
          addressesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .io.github.manojpawar94.proto.example.Address addresses = 5;</code>
       */
      public Builder clearAddresses() {
        if (addressesBuilder_ == null) {
          addresses_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          addressesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .io.github.manojpawar94.proto.example.Address addresses = 5;</code>
       */
      public Builder removeAddresses(int index) {
        if (addressesBuilder_ == null) {
          ensureAddressesIsMutable();
          addresses_.remove(index);
          onChanged();
        } else {
          addressesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .io.github.manojpawar94.proto.example.Address addresses = 5;</code>
       */
      public io.github.manojpawar94.proto.example.AddressOuterClass.Address.Builder getAddressesBuilder(
          int index) {
        return getAddressesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .io.github.manojpawar94.proto.example.Address addresses = 5;</code>
       */
      public io.github.manojpawar94.proto.example.AddressOuterClass.AddressOrBuilder getAddressesOrBuilder(
          int index) {
        if (addressesBuilder_ == null) {
          return addresses_.get(index);  } else {
          return addressesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .io.github.manojpawar94.proto.example.Address addresses = 5;</code>
       */
      public java.util.List<? extends io.github.manojpawar94.proto.example.AddressOuterClass.AddressOrBuilder> 
           getAddressesOrBuilderList() {
        if (addressesBuilder_ != null) {
          return addressesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(addresses_);
        }
      }
      /**
       * <code>repeated .io.github.manojpawar94.proto.example.Address addresses = 5;</code>
       */
      public io.github.manojpawar94.proto.example.AddressOuterClass.Address.Builder addAddressesBuilder() {
        return getAddressesFieldBuilder().addBuilder(
            io.github.manojpawar94.proto.example.AddressOuterClass.Address.getDefaultInstance());
      }
      /**
       * <code>repeated .io.github.manojpawar94.proto.example.Address addresses = 5;</code>
       */
      public io.github.manojpawar94.proto.example.AddressOuterClass.Address.Builder addAddressesBuilder(
          int index) {
        return getAddressesFieldBuilder().addBuilder(
            index, io.github.manojpawar94.proto.example.AddressOuterClass.Address.getDefaultInstance());
      }
      /**
       * <code>repeated .io.github.manojpawar94.proto.example.Address addresses = 5;</code>
       */
      public java.util.List<io.github.manojpawar94.proto.example.AddressOuterClass.Address.Builder> 
           getAddressesBuilderList() {
        return getAddressesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.github.manojpawar94.proto.example.AddressOuterClass.Address, io.github.manojpawar94.proto.example.AddressOuterClass.Address.Builder, io.github.manojpawar94.proto.example.AddressOuterClass.AddressOrBuilder> 
          getAddressesFieldBuilder() {
        if (addressesBuilder_ == null) {
          addressesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              io.github.manojpawar94.proto.example.AddressOuterClass.Address, io.github.manojpawar94.proto.example.AddressOuterClass.Address.Builder, io.github.manojpawar94.proto.example.AddressOuterClass.AddressOrBuilder>(
                  addresses_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          addresses_ = null;
        }
        return addressesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.github.manojpawar94.proto.example.Student)
    }

    // @@protoc_insertion_point(class_scope:io.github.manojpawar94.proto.example.Student)
    private static final io.github.manojpawar94.proto.example.StudentOuterClass.Student DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.manojpawar94.proto.example.StudentOuterClass.Student();
    }

    public static io.github.manojpawar94.proto.example.StudentOuterClass.Student getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Student>
        PARSER = new com.google.protobuf.AbstractParser<Student>() {
      @java.lang.Override
      public Student parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Student(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Student> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Student> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.github.manojpawar94.proto.example.StudentOuterClass.Student getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_manojpawar94_proto_example_Student_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_github_manojpawar94_proto_example_Student_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1protocol-buffer-generate-code/proto/st" +
      "udent.proto\022$io.github.manojpawar94.prot" +
      "o.example\0321protocol-buffer-generate-code" +
      "/proto/address.proto\"\310\002\n\007Student\022\022\n\nstud" +
      "ent_id\030\001 \001(\003\022\022\n\nfirst_name\030\002 \001(\t\022\021\n\tlast" +
      "_name\030\003 \001(\t\022H\n\010standard\030\004 \001(\01626.io.githu" +
      "b.manojpawar94.proto.example.Student.Sta" +
      "ndard\022@\n\taddresses\030\005 \003(\0132-.io.github.man" +
      "ojpawar94.proto.example.Address\"v\n\010Stand" +
      "ard\022\017\n\013UNKNOWN_STD\020\000\022\r\n\tFIFTH_STD\020\001\022\r\n\tS" +
      "IXTH_STD\020\002\022\017\n\013SEVENTH_STD\020\003\022\r\n\tEIGHT_STD" +
      "\020\004\022\014\n\010NINE_STD\020\005\022\r\n\tTENTH_STD\020\006b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.github.manojpawar94.proto.example.AddressOuterClass.getDescriptor(),
        });
    internal_static_io_github_manojpawar94_proto_example_Student_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_github_manojpawar94_proto_example_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_github_manojpawar94_proto_example_Student_descriptor,
        new java.lang.String[] { "StudentId", "FirstName", "LastName", "Standard", "Addresses", });
    io.github.manojpawar94.proto.example.AddressOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
