# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol-buffer-generate-code/proto/student.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protocol_buffer_generate_code.proto import address_pb2 as protocol__buffer__generate__code_dot_proto_dot_address__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protocol-buffer-generate-code/proto/student.proto',
  package='io.github.manojpawar94.proto.example',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n1protocol-buffer-generate-code/proto/student.proto\x12$io.github.manojpawar94.proto.example\x1a\x31protocol-buffer-generate-code/proto/address.proto\"\xc8\x02\n\x07Student\x12\x12\n\nstudent_id\x18\x01 \x01(\x03\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12H\n\x08standard\x18\x04 \x01(\x0e\x32\x36.io.github.manojpawar94.proto.example.Student.Standard\x12@\n\taddresses\x18\x05 \x03(\x0b\x32-.io.github.manojpawar94.proto.example.Address\"v\n\x08Standard\x12\x0f\n\x0bUNKNOWN_STD\x10\x00\x12\r\n\tFIFTH_STD\x10\x01\x12\r\n\tSIXTH_STD\x10\x02\x12\x0f\n\x0bSEVENTH_STD\x10\x03\x12\r\n\tEIGHT_STD\x10\x04\x12\x0c\n\x08NINE_STD\x10\x05\x12\r\n\tTENTH_STD\x10\x06\x62\x06proto3'
  ,
  dependencies=[protocol__buffer__generate__code_dot_proto_dot_address__pb2.DESCRIPTOR,])



_STUDENT_STANDARD = _descriptor.EnumDescriptor(
  name='Standard',
  full_name='io.github.manojpawar94.proto.example.Student.Standard',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_STD', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FIFTH_STD', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SIXTH_STD', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SEVENTH_STD', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EIGHT_STD', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NINE_STD', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TENTH_STD', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=353,
  serialized_end=471,
)
_sym_db.RegisterEnumDescriptor(_STUDENT_STANDARD)


_STUDENT = _descriptor.Descriptor(
  name='Student',
  full_name='io.github.manojpawar94.proto.example.Student',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='student_id', full_name='io.github.manojpawar94.proto.example.Student.student_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='first_name', full_name='io.github.manojpawar94.proto.example.Student.first_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='io.github.manojpawar94.proto.example.Student.last_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='standard', full_name='io.github.manojpawar94.proto.example.Student.standard', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='addresses', full_name='io.github.manojpawar94.proto.example.Student.addresses', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STUDENT_STANDARD,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=471,
)

_STUDENT.fields_by_name['standard'].enum_type = _STUDENT_STANDARD
_STUDENT.fields_by_name['addresses'].message_type = protocol__buffer__generate__code_dot_proto_dot_address__pb2._ADDRESS
_STUDENT_STANDARD.containing_type = _STUDENT
DESCRIPTOR.message_types_by_name['Student'] = _STUDENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Student = _reflection.GeneratedProtocolMessageType('Student', (_message.Message,), {
  'DESCRIPTOR' : _STUDENT,
  '__module__' : 'protocol_buffer_generate_code.proto.student_pb2'
  # @@protoc_insertion_point(class_scope:io.github.manojpawar94.proto.example.Student)
  })
_sym_db.RegisterMessage(Student)


# @@protoc_insertion_point(module_scope)
